enabled_backends = ["arch"]

hostname_groups_enabled = true

[hostname_groups]
archlinux-personal = [
  "base",
  "hardware",
  "filesystem",
  "network",
  "audio",
  "utils",
  "desktop",
  "hyprland",
  "fonts"
]

[arch]
package_manager = "yay"
