enabled_backends = ["arch"]

hostname_groups_enabled = true

[hostname_groups]
PLACEHOLDER = [
  "core",
  "base",
  "hardware",
  "audio",
  "utils",
  "fonts",
  "hyprland",
  "desktop"
]

[arch]
package_manager = "yay"
