arch = [
    # Disk tools
    "btrfs-progs",
    "gparted",
    "udisks2",
    "gvfs",
    "gvfs-mtp",
    "udiskie",

    # Archive utilities
    "xarchiver",
    "dpkg",
    "7zip",
    "unrar",
    "unzip",
    "zip"
]
