arch = [
    # Disk utilities
    "btrfs-progs",
    "gparted",
    "udisks2",
    "gvfs",
    "gvfs-mtp",
    "udiskie",

    # Archiver
    "xarchiver",
    "dpkg",
    "7zip",
    "unrar",
    "unzip",
    "zip",

    # File utilities
    "rsync"
]
