arch = [
    # AMD
    "vulkan-radeon",
    "lib32-vulkan-radeon",
    
    # Mesa
    "mesa",
    "lib32-mesa",
    "mesa-utils",
    
    # Vulkan
    "vulkan-icd-loader",
    "lib32-vulkan-icd-loader",
]
