arch = [
    # CPU microcode (AMD only)
    "amd-ucode",

    # GPU drivers (AMD only)
    "mesa",
    "lib32-mesa",
    "mesa-utils",
    "vulkan-radeon",
    "lib32-vulkan-radeon",
    "vulkan-icd-loader",
    "lib32-vulkan-icd-loader",
    "libva-mesa-driver",
    "lib32-libva-mesa-driver",

    # Power management
    "power-profiles-daemon",
]
