arch = [
    # Mesa
    "mesa-utils",

    # Drive utilities
    { package = "smartmontools", hooks = { after_install = [ "sudo", "systemctl", "enable", "--now", "smartd" ] } },
    "gparted",
    "udisks2",
    "udiskie",
    "rsync",
]
