arch = [
    # Mesa
    "libva-mesa-driver",
    "lib32-libva-mesa-driver",
    "mesa-utils",

    # Drive utilities
    { package = "smartmontools", hooks = { after_install = [ "sudo", "systemctl", "enable", "--now", "smartd" ] } },
    "gparted",
    "udisks2",
    "udiskie",

    # Performance
    "realtime-privileges"

    # Power management
    # "power-profiles-daemon"
]
