arch = [
    # AMD
    "amd-ucode",
    "vulkan-radeon",
    "lib32-vulkan-radeon",
    
    # Mesa
    "mesa",
    "lib32-mesa",
    "libva-mesa-driver",
    "lib32-libva-mesa-driver",
    "mesa-utils",
    
    # Vulkan
    "vulkan-icd-loader",
    "lib32-vulkan-icd-loader",

    # Drive utilities
    { package = "smartmontools", hooks = { after_install = [ "sudo", "systemctl", "enable", "--now", "smartd" ] } },
    "gparted",
    "udisks2",
    "udiskie",
    "rsync",
]
