arch = [
    "networkmanager-dmenu",
    { package = "openssh", hooks = { after_install = [ "sudo", "systemctl", "enable", "--now", "sshd" ] } },
    { package = "iwd", hooks = { after_install = [ "sudo", "systemctl", "enable", "--now", "iwd" ] } }
]
